### PR TITLE
Small fixes to outreach management.

### LINKED ISSUE #225: Fix bug with in student.controller.js not removing outreach from ui after deleting.

### PR DESCRIPTION
**Pull request by dting**
@pdotsani 

Resolves #225, #226, #227

### CODE REVIEW

File: server/api/outreach/index.js [hunk 1]
```diff
@@ -7,8 +7,9 @@ var auth = require('../../auth/auth.service');
 var router = express.Router();
 
 router.post('/', auth.hasRole('teacher'), controller.create);
+router.put('/:id/archive', auth.hasRole('teacher'), controller.toggleArchive);
+router.delete('/:id', auth.hasRole('teacher'), controller.delete);
+
```
Comment (pdotsani) [inline server/api/outreach/index.js]: Nice. This seems to fit with the way we configure all the other routes.

**Comment by pdotsani** [comment]
lgtm
