### PR TITLE
Fix outreach and intervention sorting.

### LINKED ISSUE #350: Sorting of outreaches reverted to most recently changed order priority.
We want the order to be stable so the server should return the outreaches in the order they were created. Timestamp order was not working because outreaches created at the same time will have the same timestamp.

### PR DESCRIPTION
**Pull request by dting**
Resolves #350.

### CODE REVIEW

**Comment by pdotsani** [comment]
lgtm.

File: server/api/student/intervention/intervention.controller.js [hunk 1]
```diff
@@ -10,10 +10,13 @@ var Student = require('../student.model');
...
  */
 exports.index = function(req, res) {
-  Intervention.find({student: req.student.id}, function(err, interventions) {
-    if (err) return handleError(res, err);
-    return res.status(201).json(interventions);
-  });
+  Intervention
+    .find({student: req.student.id})
+    .sort({_id: -1})
+    .exec(function(err, interventions) {
```
Comment (pdotsani) [inline server/api/student/intervention/intervention.controller.js]: Is the date specified in the mongodbId more specific? Or is it sorting on other criteria?

Comment (dting) [inline server/api/student/intervention/intervention.controller.js]: It isn't more specific but the id includes something that allows it to sort when timestamp is the same by insertion order:

http://stackoverflow.com/questions/12098815/mongodb-sort-order-on-id
